// Generated by CoffeeScript 1.6.2
(function() {
  var a, b, fadeIn, i, image, imageArray, imageArrayTag, next, previous, timer, tracker;

  image = document.getElementById('image');

  imageArrayTag = document.getElementsByTagName('img');

  imageArray = [];

  tracker = void 0;

  timer = void 0;

  i = 0;

  while (i < imageArrayTag.length) {
    imageArray.push(imageArrayTag[i].src);
    i += 1;
  }

  fadeIn = function() {
    if (image.style.opacity >= 1) {
      return;
    }
    return image.style.opacity = parseFloat(image.style.opacity, 10) + 0.01;
  };

  next = function() {
    var _i, _ref;

    image.style.opacity = 0;
    for (i = _i = 0, _ref = imageArray.length; _i <= _ref; i = _i += 1) {
      if (image.src === imageArray[i]) {
        if (image.src === imageArray[imageArray.length - 1]) {
          tracker = imageArray[0];
        } else {
          tracker = imageArray[i + 1];
        }
      }
    }
    return image.src = tracker;
  };

  previous = function() {
    var _i, _ref;

    image.style.opacity = 0;
    for (i = _i = 0, _ref = imageArray.length; _i <= _ref; i = _i += 1) {
      if (image.src === imageArray[0]) {
        if (image.src === imageArray[0]) {
          tracker = imageArray[imageArray.length(-1)];
        } else {
          tracker = imageArray[i - 1];
        }
      }
    }
    return image.src = tracker;
  };

  a = document.getElementById('next');

  b = document.getElementById('previous');

  a.onclick = function() {
    clearInterval(timer);
    timer = setInterval(fadeIn, 10);
    return next();
  };

  b.onclick = function() {
    clearInterval(timer);
    timer = setInterval(fadeIn, 10);
    return previous();
  };

}).call(this);
